### PR TITLE
Add custom page template to avoid showing featured image

### LINKED ISSUE #932: Featured Images on Pages
When choosing a Featured Image on a page, the image becomes huge. This means that open graph tags pick up whatever the first image on the page is, which can lead to unintended consequences on pages like "Share your Work," which picks up the Flickr logo on social: https://creativecommons.org/share-your-work/

I'd like to be able to add a featured image to a page without it showing up on the page as a massive image.

### PR DESCRIPTION
**Pull request by hugosolar**
Fixes creativecommons/creativecommons.org#932

**Description**
added page template to theme in order to avoid showing the featured image as requested in  creativecommons/creativecommons.org#932
In case that an editor needs to put a featured image on some page, it should be added in the WP editor

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Review by kgodey — COMMENTED** [review]
@hugosolar will this affect older posts? how do we make sure that sharing older posts will still show the correct image, or is that not a concern?

also, please talk with @ericsteuer about this change so that we can make sure to set featured images manually

**Comment by hugosolar** [comment]
Yes, this will affect the older post, but as far as I know we do not use feature image on pages because of the same reason, the current CC WordPress theme doesn't seem to have a nice integration with the twentysixteen layout. 
I'll check the current pages in use to see if there is any featured image in use. Also will talk to Eric about this

**Comment by ericsteuer** [comment]
Thanks. Once Victoria starts (on Monday), let's find some quick time to
discuss whether there is anything that should happen / not happen in
Wordpress posts to make sure pages don't look wonky.

**Comment by hugosolar** [comment]
hey @kriti, I've checked all the current pages in use and no one of them uses the Wordpress featured image, just images used in the Wordpress editor. I think this happens because you can't add attribution information into featured images, I mean, you can but it's not reflected on the page.

**Comment by kgodey** [comment]
I think we're good to merge then. We can go over how to use featured images with Victoria and Eric once merged.

**Review by kgodey — APPROVED** [review]

**Comment by ericsteuer** [comment]
Hi, I'm not sure how exactly this is related, but I just published this
blog post:
https://creativecommons.org/2019/08/26/self-magazine-and-the-aap-promote-vaccine-awareness-through-cc-licensed-images/

And I was unable to find in the new theme how to select it as a "featured"
or "hero" post, so that it will show up on the CC homepage

**Comment by hugosolar** [comment]
This was caused by the Wordpress update and the replacement of the editor, Somehow, the new editor do not show the highlight taxonomy (which contains those categories).
I switch to the classic editor in the meantime while we update the way that news are shown

**Comment by ericsteuer** [comment]
Thanks very much. For what it's worth, the new editor is MUCH better -- but
just is missing the ability to highlight certain posts.

**Pull request merged**
